language: java
jdk: openjdk8
sudo: false
script: mvn clean install
cache:
  directories:
    - $HOME/.m2

install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

