version: '3'
services:
  server:
    container_name: server
    image: texastoc-v4-h2-image:latest
    environment:
      SPRING_APPLICATION_JSON: >
        {
          "db": {
            "h2": true,
            "mysql": false,
            "schema": true,
            "seed": true,
            "populate": true
          }
        }
    ports:
      - 8080:8080
  client:
    container_name: client
    image: texastoc-v4-ui-image:latest
    environment:
      - REACT_APP_CLIENT_URL=https://localhost
      - REACT_APP_SERVER_URL=https://localhost
    ports:
      - 3000:3000
    depends_on:
      - server
