
export const API_ERROR = 'API_ERROR'
export const API_ERROR_DONE = 'API_ERROR_DONE'
export const GOT_LEAGUE_PLAYERS = 'GOT_LEAGUE_PLAYERS'
export const EDIT_LEAGUE_PLAYER = 'EDIT_LEAGUE_PLAYER'
export const REDIRECT = 'REDIRECT'
export const RESET = 'RESET'
export const REFRESH = 'REFRESH'
export const VERSION_CHECK = 'VERSION_CHECK'
export const NEW_VERSION = 'NEW_VERSION'
export const WAITING = 'WAITING'
