
export const TOGGLE_ADD_PLAYER_TO_GAME = 'TOGGLE_ADD_PLAYER_TO_GAME'
export const TOGGLE_CONFIGURE_SEATING = 'TOGGLE_CONFIGURE_SEATING'
export const EDIT_GAME_PLAYER = 'EDIT_GAME_PLAYER'
export const GETTING_CURRENT_GAME = 'GETTING_CURRENT_GAME'
export const CURRENT_GAME_NOT_FOUND = 'CURRENT_GAME_NOT_FOUND'
export const GOT_CURRENT_GAME = 'GOT_CURRENT_GAME'
export const ADDED_NEW_GAME = 'ADDED_NEW_GAME'
export const SEATING_NOTIFIED = 'SEATING_NOTIFIED'
